name: Logs Source
language: csharp
variables:
  - name: output_metrics
    inputType: OutputTopic
    description: ''
    defaultValue: k8s-metrics
    required: true
  - name: K8SEndpoint
    inputType: Secret
    description: ''
    defaultValue: K8SEndpoint
    required: true
  - name: K8SClusterCertificateAuthorityData
    inputType: Secret
    description: ''
    defaultValue: K8SClusterCertificateAuthorityData
    required: true
dockerfile: dockerfile
runEntryPoint: WriteHelloWorld.csproj
defaultFile: WriteHelloWorld/Program.cs
