name: Logs Source
language: csharp
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic
    defaultValue: k8s-logs
    required: true
dockerfile: dockerfile
runEntryPoint: WriteHelloWorld.csproj
defaultFile: WriteHelloWorld/Program.cs
