name: Logs Source
language: python
variables:
  - name: output_metrics
    inputType: OutputTopic
    description: ''
    defaultValue: k8s-metrics
    required: true
  - name: K8SEndpoint
    inputType: Secret
    description: ''
    defaultValue: K8SEndpoint
    required: true
  - name: K8SClusterCertificateAuthorityData
    inputType: Secret
    description: ''
    defaultValue: K8SClusterCertificateAuthorityData
    required: true
  - name: K8SClientCertificateData
    inputType: Secret
    description: ''
    defaultValue: K8SClientCertificateData
    required: true
  - name: K8SClientKeyData
    inputType: Secret
    description: ''
    defaultValue: K8SClientKeyData
    required: true
  - name: K8SToken
    inputType: Secret
    description: ''
    defaultValue: K8SToken
    required: true
  - name: K8SClusterName
    inputType: FreeText
    description: ''
    defaultValue: DevCluster
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
