name: Threshold alert
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for raw data
    defaultValue: k8s-metrics
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic for alerts
    defaultValue: metrics-alerts
    required: true
  - name: parameterName
    inputType: FreeText
    description: This is the stream's parameter to track
    defaultValue: memory
    required: true
  - name: thresholdValue
    inputType: FreeText
    description: This is the threshold's numerical value
    defaultValue: 100
    required: true
  - name: bufferMilliSeconds
    inputType: FreeText
    description: How long to wait before waiting for threshold checking (milliseconds)
    defaultValue: 1
    required: true
  - name: METRIC_TYPE
    inputType: FreeText
    description: ''
    defaultValue: pod
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: threshold_function.py
